services:
  - type: web
    name: blog-application
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn myblog.wsgi:application --chdir myblog
    envVars:
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blog-application-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: blog-application.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://blog-application.onrender.com

databases:
  - name: blog-application-db
    plan: free
